pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/iHarshal08/DevOps_Calc_miniProject.git'
            }
        }
        stage('Build') {
            steps {
                sh 'g++ -o calculator src/calculator.cpp'
            }
        }
        stage('Test') {
            steps {
                sh './calculator'
            }
        }
        stage('Docker Build & Push') {
            steps {
                sh 'docker build -t iharshal/calculator-app -f docker/Dockerfile .'
                sh 'docker login -u iharshal -p Harshal@p0808'
                sh 'docker push iharshal/calculator-app'
            }
        }
    }
}
