pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/iHarshal08/DevOps_Calc_miniProject.git' 
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t calculator-app -f docker/Dockerfile .'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'docker run --rm calculator-app'  // Run calculator inside Docker
            }
        }

        stage('Deploy (Using Ansible)') {
            steps {
                sh 'ansible-playbook ansible/deploy.yml'
            }
        }
    }
}
